# sprdbt_tty - Moto G20 (java) Unisoc BT controller-transport driver
# Reconstruction v1 (M4 deep binary reconstruction, ABI-PASS 85/85)
obj-$(CONFIG_SPRDBT_TTY) += sprdbt_tty.o
sprdbt_tty-y := tty.o lpm.o rfkill.o dump.o alignment/sitm.o
ccflags-y += -Wno-error
