# sprdbt_tty.ko - source from ud710_bsp@W20.13.3
# modules/wcn/bluetooth/driver/tty-sdio (+alignment); -DDEBUG per factory Kbuild.
# Build-rule adaptation: the factory BSP build provided the in-tree sprdwcn
# include paths; an out-of-tree M= build must add them explicitly.
obj-m := sprdbt_tty.o
sprdbt_tty-y := dump.o lpm.o rfkill.o alignment/sitm.o tty.o
ccflags-y += -DDEBUG \
	-I$(srctree)/drivers/misc/sprdwcn/include \
	-I$(srctree)/drivers/misc/sprdwcn/boot \
	-I$(srctree)/drivers/misc/sprdwcn/platform \
	-I$(srctree)/drivers/misc/sprdwcn/pcie \
	-I$(srctree)/drivers/misc/sprdwcn/platform/rf
